version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: nodevault-mongo
    restart: unless-stopped
    volumes:
      - nodevault-mongo-data:/data/db
    networks:
      - nodevault-net

  backend:
    build: .  # Build from Dockerfile in current folder
    container_name: nodevault-backend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Map container 3000 -> host 3000
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://nodevault-mongo:27017/nodevault
    depends_on:
      - mongo
    networks:
      - nodevault-net

volumes:
  nodevault-mongo-data:

networks:
  nodevault-net:
    driver: bridge

